spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 111
#    password: root
    hikari:
      pool-name: DataHikariCP
      minimum-idle: 5
      #空闲连接时间，半小时
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
#      心跳机制
      connection-test-query: SELECT 1

  redis:
#    host: 192.168.139.100
#    host:
    host: localhost
    port: 6379
#    password: 123456
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.example.seckill.pojo

logging:
  level:
    com.example.seckill.mapper: debug
